
SET(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
SET(PARAVIEW_USE_MPI ON CACHE BOOL "" FORCE)
SET(PARAVIEW_ENABLE_PYTHON ON CACHE BOOL "" FORCE)
SET(PARAVIEW_BUILD_QT_GUI OFF CACHE BOOL "" FORCE)
SET(ENABLE_MPI4PY OFF CACHE BOOL "" FORCE)
SET(VTK_USE_X OFF CACHE BOOL "" FORCE)
SET(BUILD_TESTING OFF CACHE BOOL "" FORCE)


SET(CMAKE_BUILD_TYPE "Release" CACHE STRING "" FORCE)
SET(CMAKE_CXX_FLAGS_RELEASE "-O2 -qstrict -qarch=450d -qtune=450 -qcpluscmt" CACHE STRING "" FORCE)


SET(VTK_USE_SYSTEM_HDF5 ON CACHE BOOL "" FORCE)
SET(HDF5_INCLUDE_DIR /soft/apps/current/hdf5-1.8.5-patch1/include CACHE PATH "" FORCE)
SET(HDF5_INCLUDE_DIRS /soft/apps/current/hdf5-1.8.5-patch1/include CACHE PATH "" FORCE)
SET(HDF5_LIBRARY /soft/apps/current/hdf5-1.8.5-patch1/lib/libhdf5.a CACHE FILEPATH "" FORCE)
SET(HDF5_LIBRARIES /soft/apps/current/hdf5-1.8.5-patch1/lib/libhdf5.a CACHE FILEPATH "" FORCE)


SET(VTK_USE_SYSTEM_ZLIB ON CACHE BOOL "" FORCE)
SET(ZLIB_INCLUDE_DIR /soft/apps/current/zlib-1.2.5/include CACHE PATH "" FORCE)
SET(ZLIB_LIBRARY /soft/apps/current/zlib-1.2.5/lib/libz.a CACHE FILEPATH "" FORCE)

SET(PYTHON_UTIL_LIBRARY
/bgsys/drivers/ppcfloor/gnu-linux/powerpc-bgp-linux/lib/libutil.a;/bgsys/drivers/ppcfloor/gnu-linux/powerpc-bgp-linux/lib/libdl.a
CACHE FILEPATH "" FORCE)